version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "order-app"
s3_bucket = "serverless-stack-workshop-20231127"
s3_prefix = "order-app"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
